# test and deploy service on push to main

name: release

env:
  CACHE_KEY_PREFIX: aspnet-uttt
  WORKING_DIRECTORY: aspnet

on:
  push:
    branches: 
      - main

jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
      - name: actions_checkout
        uses: actions/checkout@v2
      - name: dotnet_cache
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('**/packages.lock.json') }}
      - name: dotnet_restore
        run: dotnet restore
        working-directory: ${{ env.WORKING_DIRECTORY }}

  build:
    name: build_aspnet
    needs: restore
    runs-on: ubuntu-latest
    steps:
      - name: actions_checkout
        uses: actions/checkout@v2
      - name: dotnet_cache
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('**/packages.lock.json') }}
      - name: dotnet_build
        run: dotnet build
        working-directory: ${{ env.WORKING_DIRECTORY }}
  
  test:
    name: test_aspnet
    needs: restore
    runs-on: ubuntu-latest
    steps:
      - name: actions_checkout
        uses: actions/checkout@v2
      - name: dotnet_cache
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('**/packages.lock.json') }}
      - name: dotnet_test
        run: |
          dotnet test \
          -p:CollectCoverage=true \
          -p:CoverletOutput=../code_coverage/ \
          -p:CoverletOutputFormat=opencover \
          --logger trx \
          --results-directory ./test_coverage/
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - name: opencover_upload
        uses: actions/upload-artifact@v1.0.0
        with:
          name: code_coverage
          path: ${{ env.WORKING_DIRECTORY }}/code_coverage
      - name: trx_upload
        uses: actions/upload-artifact@v1.0.0
        with:
          name: test_coverage
          path: ${{ env.WORKING_DIRECTORY }}/test_coverage
  
  analyze:
    name: analyze_aspnet
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: actions_checkout
        uses: actions/checkout@v2
      - name: git_fetch
        run: git fetch --unshallow
      - name: opencover_download
        uses: actions/download-artifact@v1.0.0
        with:
          name: code_coverage
          path: ${{ env.WORKING_DIRECTORY }}/code_coverage
      - name: trx_download
        uses: actions/download-artifact@v1.0.0
        with:
          name: test_coverage
          path: ${{ env.WORKING_DIRECTORY }}/test_coverage
      - name: sonar_install
        run: dotnet tool install --global dotnet-sonarscanner
      - name: dotnet_cache
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('**/packages.lock.json') }}
      - name: sonar_scan
        run: |
          dotnet sonarscanner begin -k:uttt-svc -o:ultimate-tic-tac-toe -s:$(pwd)/sonar.analysis.xml
          dotnet build
          dotnet sonarscanner end
        working-directory: ${{ env.WORKING_DIRECTORY }}
  
  # pack:
  #   name: pack_aspnet
  #   runs-on: ubuntu-latest
  
  # deploy:
  #   name: deploy_aspnet
  #   runs-on: ubuntu-latest